### PR TITLE
Insert into LittleDict when there is a single Pair

### LINKED ISSUE #27: LittleDict{Symbol,Int}(:x=>1) throws error
```julia
# work fine:
LittleDict(:x=>1)
Dict{Symbol,Int}(:x=>1)

# throws error:
LittleDict{Symbol,Int}(:x=>1)
ERROR: ArgumentError: LittleDict(kv): kv needs to be an iterator of tuples or pairs
Stacktrace:
 [1] LittleDict{Symbol,Int64,KS,VS} where VS<:(Union{#s14, #s13} where #s13<:(Array{T,1} where T) where #s14<:Tuple) where KS<:(Union{#s14, #s13} where #s13<:(Array{T,1} where T) where #s14<:Tuple)(::Pair{Symbol,Int64}) at /Users/anthony/.julia/packages/OrderedCollections/E21Rb/src/little_dict.jl:58
 [2] top-level scope at REPL[25]:1
```

### PR DESCRIPTION
**Pull request by eulerkochy**
Fixes #27

### CODE REVIEW

File: src/little_dict.jl [hunk 1]
```diff
@@ -75,6 +75,9 @@ LittleDict(itr::T) where T = LittleDict{kvtype(eltype(T))...}(itr)
 LittleDict(itr1::Pair, itr2::Pair) = LittleDict(first.([itr1, itr2]), last.([itr1,itr2]))
 LittleDict(itr1::Pair) = LittleDict([first(itr1)], [last(itr1)])
```
Comment (oxinabox) [inline src/little_dict.jl]: This line can be deleted, no?

Comment (eulerkochy) [reply src/little_dict.jl]: Yes, probably. The problem arises in the test specific to these lines. The definition of the declaration wasn't clear to me, so I was waiting for your review.

Comment (eulerkochy) [reply src/little_dict.jl]:
```
julia> d = LittleDict((1, 2), ("a", "b"))
LittleDict{Int64,String,Tuple{Int64,Int64},Tuple{String,String}} with 2 entries:
  1 => "a"
  2 => "b"
```
removing the lines have this effect on the definition.

Comment (oxinabox) [reply src/little_dict.jl]: That looks correct to me.
The `LittleDict(keys::Tuple, vals::Tuple)` constructor should take priority over:
`LittleDict(kv1, kv2)`
as `keys::Tuple, vals::Tuple` is the pattern to avoid allocations.

Comment (eulerkochy) [reply src/little_dict.jl]: Cool. But the tests have 
```
@test d[1] === 2
@test d["a"] == "b"
```
which should be omitted, on allowing this definition

Comment (oxinabox) [reply src/little_dict.jl]: Yes, i think those tests were just wrong.
But apparently past-me disagreed.
So it bears more thinking.

Comment (oxinabox) [reply src/little_dict.jl]: These tests are fine and have the correct behavour:

https://github.com/JuliaCollections/OrderedCollections.jl/blob/bc0407699942c1b92585080d4519556dc0fa2023/test/test_little_dict.jl#L273-L279

None of them are `LittleDict(::Tuple, ::Tuple)`
they are either `LittleDict(::Pair, ::Pair)` and `LittleDict(::Tuple)` and `LittleDict(::Vector)`

Comment (eulerkochy) [reply src/little_dict.jl]: Well, travis failed on these particular testset, so I assumed something must be off here itself.
And moreover, 
```
julia> d = LittleDict((1, 2), ("a", "b"))
LittleDict{Int64,String,Tuple{Int64,Int64},Tuple{String,String}} with 2 entries:
  1 => "a"
  2 => "b"
```
and the tests can't be simultaneously true, assuming if I drop 
```
LittleDict(itr1::Pair, itr2::Pair) = LittleDict(first.([itr1, itr2]), last.([itr1,itr2]))
LittleDict(itr1::Pair) = LittleDict([first(itr1)], [last(itr1)])
```

Comment (oxinabox) [reply src/little_dict.jl]: > and the tests can't be simultaneously true, assuming if I drop

Why not?
There is no test for that.

The tests are:
```
 d = LittleDict(((1, 2), ("a", "b")))   # LittleDict(::Tuple)`
 d2 = LittleDict([(1, 2), ("a", "b")])   # LittleDict(::Vector)
 d3 = LittleDict(1 => 2, "a" => "b")   # LittleDict(::Pair, ::Pair)
 d4 = LittleDict((1 => 2, "a" => "b"))   # LittleDict(::Tuple)
```


`LittleDict((1, 2), ("a", "b"))` is `LittleDict(::Tuple, ::Tuple)`

Comment (eulerkochy) [reply src/little_dict.jl]: the problem arises due to 
`d = LittleDict(((1, 2), ("a", "b")))`
It's a `Tuple{Tuple{Int64,Int64},Tuple{String,String}}`.
if you glance at my implementation, this ctor call triggers a call to my ctor in which `K` is `Tuple{Int64, Int64}` and `V` is `Tuple{String, String}`. I'll probably hack into my implementation to see if I can work around without this line getting triggered. Probably, that will be sufficient.

Comment (eulerkochy) [reply src/little_dict.jl]: @oxinabox I've done a bit of hackery to handle the case. And you were right, I was worried about the wrong test case the whole time :sweat_smile:

File: src/little_dict.jl [hunk 2]
```diff
@@ -54,6 +54,8 @@ LittleDict(ks, vs) = LittleDict(collect(ks), collect(vs))
 function LittleDict{K,V}(itr) where {K,V}
     ks = K[]
     vs = V[]
+    # handle the special case of a single Pair
+    itr isa Pair{K, V} && return LittleDict([first(itr)], [last(itr)])
```
Comment (oxinabox) [inline src/little_dict.jl]: Can we make this a top level method?

maybe
`LittleDict{K,V}(single_item::Union{Pair{K,V}, Tuple{K,V}} where {K,V}`

Following the more general pattern of:
Replace `if x isa` with a new method for multiple-dispatch

**Comment by oxinabox** [comment]
I had a play, and I think the cleanest way to solve this is to add the dispatch:
```julia
LittleDict{K, V}(itr::Pair) where {K, V} = LittleDict{K,V}(K[first(itr)], V[last(itr)])
```
This is basically the same as what you have, in that it is the first few lines of the `LittleDict{K,V}(itr)` method.
But it is written as a top level method.

Note the lack of constraints on the `Pair`, but the type constrained vectors in 
On to line 79.
The problem is the same as the problem line 78 is solving.
So that is where it belongs


And the testset to use, I think should be extended somewhat:
```julia
        d = LittleDict{Symbol, Int}(:x=>1)
        d1 = LittleDict(:x=>1)
        d_wide = LittleDict{Symbol, Number}(:x=>1)
        @test d == d1 == d_wide
        @test d isa LittleDict{Symbol, Int}
        @test d1 isa LittleDict{Symbol, Int}
        @test d_wide isa LittleDict{Symbol, Number}

        @test_throws MethodError LittleDict{Char,Char}(:x => 1)
```

Note the check on a non-exact type, 
and the check we get expected errors (unhappy path test). 

Possibly the testset should be broken up a little more. I'm not sure.

**Comment by eulerkochy** [comment]
Sure thing! That's a neat way to do it! And yes, the tests need to expand as well. I would have normally done that. I don't know how I missed it. 

Yes, I noticed that `kvtype` thing on L78-79, and wasn't exactly sure, why it was meant that way. I haven't followed the development of `LittleDict`, so I wasn't exactly where to mess with or not.

**Comment by eulerkochy** [comment]
@oxinabox the above implementation leads to a strange problems
```
julia> d = LittleDict{Any, Int}(:x=>1)
LittleDict{Any,Int64,Array{Any,1},Array{Int64,1}} with 1 entry:
  :x => 1

julia> d1 = LittleDict{Any, Any}(:x=>1)
LittleDict{Any,Any,Array{Any,1},Array{Any,1}} with 1 entry:
  :x => 1

julia> using Test

julia> @test d == d1
Test Passed
```
Is this expected behavior? Because imho, if the underlying containers types are different, the `==` should hold

**Comment by oxinabox** [comment]
> Is this expected behavior? Because imho, if the underlying containers types are different, the == shouldn't hold

Matches to `Base`.

```
julia> d1 = Dict{Any, Any}(:x=>1)
Dict{Any,Any} with 1 entry:
  :x => 1

julia> d2 = Dict{Symbol, Int}(:x=>1)
Dict{Symbol,Int64} with 1 entry:
  :x => 1

julia> d1 == d2
true
```

Also we check that this is the case here:
https://github.com/JuliaCollections/OrderedCollections.jl/blob/7eb947b33f79806cf204423327572d1a65962aef/test/test_little_dict.jl#L330
(though I too found it weird so left a comment)

File: test/test_little_dict.jl [hunk 3]
```diff
@@ -489,6 +489,7 @@ using OrderedCollections: FrozenLittleDict, UnfrozenLittleDict
         @test d_wide isa LittleDict{Symbol, Number}
 
         @test_throws MethodError LittleDict{Char,Char}(:x => 1)
+        @test isequal(LittleDict{Int,Int}(), LittleDict{AbstractString,AbstractString}())
```
Comment (oxinabox) [inline test/test_little_dict.jl]: this is unrelete the that issue, but you can put it further up in this file with the other `isequal` tests

Comment (eulerkochy) [reply test/test_little_dict.jl]: Ohh! It's already there :sweat_smile:

Comment (eulerkochy) [reply test/test_little_dict.jl]: Just now, I saw your comment in the corresponding testset! Yes, it's sort of a descriptive comparison, rather than absolute equality.

**Comment by eulerkochy** [comment]
@oxinabox is there a problem with nighly builds ? Appveyor is failing on nightly, since yesterday

File: src/little_dict.jl [hunk 4]
```diff
@@ -54,7 +54,7 @@ LittleDict(ks, vs) = LittleDict(collect(ks), collect(vs))
 function LittleDict{K,V}(itr) where {K,V}
     ks = K[]
     vs = V[]
-    for val in itr
+   for val in itr
```
Comment (oxinabox) [inline src/little_dict.jl]: 😂  idk how one space got deleted here

```suggestion
    for val in itr
```

**Comment by oxinabox** [comment]
LGTM merge when ready
