### PR TITLE
RFC: Fix rehash check

### LINKED ISSUE #65: Bug in OrderedDict (unlike in LittleDict, and Dict)
Copied the test from Base, where with Dict is ok, here renamed to OrderedDict not:

```
using Tests
@testset "shallow and deep copying" begin
           a = Any[[1]]
           q = QuoteNode([1])
           ca = copy(a); dca = @inferred(deepcopy(a))
           @test ca !== a
           @test ca[1] === a[1]
           @test dca !== a
           @test dca[1] !== a[1]
           @test deepcopy(q).value !== q.value
       
           @test_throws ErrorException("deepcopy of Modules not supported") deepcopy(Base)
       
           # deepcopy recursive dicts
           x = OrderedDict{OrderedDict, Int}()
           x[x] = 0
           @test length(deepcopy(x)) == 1
       end
```

### PR DESCRIPTION
**Pull request by kmsquire**
* We should(?) rehash when 3/4 of the slots have been deleted, not when 3/4
  of the keys have been deleted.  The previous logic caused us to rehash
  when, e.g., there were 5 keys and we deleted 4.  The new logic
  requires at least 12 removals before a size-based rehash occurs.

The main bug with the previous logic was when the number of keys was less than 4, we would always rehash.  See below for an alternative fix.

It's arguable what the best strategy is...

Either fix below fixes #65.

### CODE REVIEW

File: src/ordered_dict.jl [hunk 1]
```diff
@@ -311,7 +311,7 @@ function _setindex!(h::OrderedDict, v, key, index)
     sz = length(h.slots)
     cnt = nk - h.ndel
     # Rehash now if necessary
-    if h.ndel >= ((3*nk)>>2) || cnt*3 > sz*2
+    if h.ndel >= ((3*sz)>>2) || cnt*3 > sz*2
```
Comment (kmsquire) [inline src/ordered_dict.jl:314]: Previously, when `nk` was less than 4, we would rehash every time.  This was probably unintended.

The fix here mimics `Base.Dict`, but the implementation there is different--keys are stored in an array the same shape/length as slots, whereas here, the keys are stored in a shorter vector that, after rehash, is only as long as the number of keys.  (`nk` here is the number of keys before rehash--i.e., it includes deleted keys.)

This might suggest that the strategy should be different.  An alternative could be, e.g. 

```suggestion
    if h.ndel >= ((3*nk)>>2) >= 3 || cnt*3 > sz*2
```

which basically requires at least 4 keys before anything happens.

**Comment by eulerkochy** [comment]
Well, I'm in for this change, given that for general use cases(e.g batch deletion followed by batch insertion), this will be quite useful.

**Review by eulerkochy — APPROVED** [review]

**Comment by fingolfin** [comment]
Thank you for your contribution. I hope this can be merged soon (after almost 4 years of delay, oops)

**Review by fingolfin — APPROVED** [review]
